### PR TITLE
Cadeau mask

### PR DESCRIPTION
**Pull request by jacopo-exact**
NOTE: please merge PR #6 first!

This PR introduces a minimal refactoring of the CADEAU mask generation routines, introducing minimal modularisation so that it can be included in MER.

The directory structure contained a name that is not compatible with python package names (`static-data`). The hyphen was turned into an underscore and a symbolic link introduced to maintain backward compatibility with scripts that purely rely on path instead of relying on the import system.

cc @spiani

### CODE REVIEW

**Comment by spiani** [comment]
The `static-data` directory was intended solely for storing static data used to generate the masks, not for housing Python code. While there are some Python scripts in the directory, they aren't part of the package itself. These are external scripts specifically for generating the meshmasks (I think). I didn’t write the scripts in static-data, but I would expect them to import `MITgcm_BC_IC` as an external package. If we adjust the scripts to work this way, can we maintain the current structure? Having two directories with similar names, where one links to the other, doesn’t seem very clean to me.

**Comment by jacopo-exact** [comment]
indeed it is not. However heavily refactoring mitgcm.bc_ic is out of scope for the mer project.

what i did was the minimal change to
1. solve import issues
2. maintain backward compatiblity.

I understand that `static-data` was created to store static data, but alas somebody decided it was a good place to store scripts too, and mer needs to import those scripts.

The scripts never import from bc_ic, only from bitsea.

**Comment by spiani** [comment]
Ok, if these scripts are separated from the package, would it be feasible to integrate them in a proper way inside the mer project? Probably we will need just one or two of them (I hope), and they should be quite short.
In this way, they would find their place in this world and they will be integrated with the mer CLI (otherwise, I think that we need to call them as separated scripts). My only concern is that that this may be too time-consuming. What do you think?

**Comment by jacopo-exact** [comment]
i can definitely embed them in the `mer/legacy/` subpackage and close this PR. The only annoying thing is that there might be some dependencies that are carried over.

**Comment by jacopo-exact** [comment]
I vendored the cadeau maskgen script by embedding it in mer (cf. https://github.com/inogs/mer/pull/60). This changeset is no longer needed and I'm closing the PR.

**Pull request closed without merging**
